import type { Book } from "@/components/book-card";

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "The Alchemist's Secret",
    author: "Paulo Coelho",
    coverImage: "https://picsum.photos/seed/book1/300/450",
    imageHint: "desert landscape",
    genre: "Fantasy",
    rating: 4.5,
    description: "A fable about following your dream.",
  },
  {
    id: "2",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    coverImage: "https://picsum.photos/seed/book2/300/450",
    imageHint: "evolution chart",
    genre: "Non-Fiction",
    rating: 4.8,
    description: "A look into the history of humankind.",
  },
  {
    id: "3",
    title: "Atomic Habits",
    author: "James Clear",
    coverImage: "https://picsum.photos/seed/book3/300/450",
    imageHint: "gears turning",
    genre: "Self-Help",
    rating: 4.9,
    description: "An easy & proven way to build good habits & break bad ones.",
  },
  {
    id: "4",
    title: "Dune",
    author: "Frank Herbert",
    coverImage: "https://picsum.photos/seed/book4/300/450",
    imageHint: "sand dunes",
    genre: "Sci-Fi",
    rating: 4.7,
    description: "A classic of science fiction, an epic of the far future.",
  },
  {
    id: "5",
    title: "Nineteen Eighty-Four",
    author: "George Orwell",
    coverImage: "https://picsum.photos/seed/book5/300/450",
    imageHint: "eye watching",
    genre: "Dystopian",
    rating: 4.6,
    description: "A dystopian social science fiction novel and cautionary tale.",
  },
  {
    id: "6",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    coverImage: "https://picsum.photos/seed/book6/300/450",
    imageHint: "fantasy landscape",
    genre: "Fantasy",
    rating: 4.8,
    description: "A children's fantasy novel, the prelude to The Lord of the Rings.",
  },
   {
    id: "7",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    coverImage: "https://picsum.photos/seed/book7/300/450",
    imageHint: "regency couple",
    genre: "Romance",
    rating: 4.7,
    description: "A romantic novel of manners written by Jane Austen in 1813.",
  },
  {
    id: "8",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    coverImage: "https://picsum.photos/seed/book8/300/450",
    imageHint: "mockingbird silhouette",
    genre: "Classic",
    rating: 4.8,
    description: "A novel about the seriousness of the problems of racism and injustice.",
  },
];
